/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiCrimeNamesRouteImport } from './routes/api/crime-names'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiWxRouteImport } from './routes/api/wx'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrimeNamesRoute = ApiCrimeNamesRouteImport.update({
  id: '/api/crime-names',
  path: '/api/crime-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWxRoute = ApiWxRouteImport.update({
  id: '/api/wx',
  path: '/api/wx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/wx': typeof ApiWxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/wx': typeof ApiWxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/wx': typeof ApiWxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/crime-names'
    | '/api/markets'
    | '/api/news'
    | '/api/wx'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/crime-names'
    | '/api/markets'
    | '/api/news'
    | '/api/wx'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/crime-names'
    | '/api/markets'
    | '/api/news'
    | '/api/wx'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiCrimeNamesRoute: typeof ApiCrimeNamesRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiWxRoute: typeof ApiWxRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crime-names': {
      id: '/api/crime-names'
      path: '/api/crime-names'
      fullPath: '/api/crime-names'
      preLoaderRoute: typeof ApiCrimeNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wx': {
      id: '/api/wx'
      path: '/api/wx'
      fullPath: '/api/wx'
      preLoaderRoute: typeof ApiWxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiCrimeNamesRoute: ApiCrimeNamesRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiWxRoute: ApiWxRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
